name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p
    - name: Print destinations
      run: xcodebuild -project Lumiform/Lumiform.xcodeproj -scheme "LumiformTests" -showdestinations -sdk macosx
    - name: Build & Run tests on macOS
      run: xcodebuild clean build test -project Lumiform/Lumiform.xcodeproj -scheme "LumiformTests" -sdk macosx -destination 'platform=macOS, arch=arm64' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES